### ISSUE TITLE
Problem re-running TriDiMap GUI

### ISSUE THREAD

**Issue by MGRashed** [DavidMercier/TriDiMap#20]
There might be some issues with TriDiMap as when I exit it once and try to re-run the demo.m file. This is the message being displayed in the command window - https://i.imgur.com/n4rdCtl.jpg

I have to kill the MATLAB instance as it freezes and restart a new session.

**Comment by DavidMercier** [comment]
It sounds, it's a "clear all", which brings this error:
https://fr.mathworks.com/matlabcentral/answers/420712-clear-all-returns-warning-evaluatecode-m-could-not-be-cleared-because-it-contains-the-code-that-is-c

But, in TriDiMap there is just a clear all at the top of "demo.m" script to run the main GUI.
I don't really see what could be the problem, or it could be that a fitting process is not finished, like the fit of PDF plot. To be investigated...

**Comment by DavidMercier** [comment]
I removed useless "clear all" at the beginning of the demo.m function.
Now it works perfectly, without any warning/error anymore... See commit #353.
